### ISSUE TITLE
Stellar Staging - All transaction history is lost in the conversion

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3bot_wallet#106]
**Repro steps**
1) Convert from revine to stellar
2) Check transaction history

**Expected Result**
The transaction history is still there

**Actual Result**
All transaction history is gone

**System Info**

**Comment by ken-de-moor** [comment]
@tobiaschielens @JonasWijne @jdelrue 

I know this is a technical choice, but I still created the issue to ensure all parties are aware of this result. And if maybe customers need to be informed that they should save their transaction history somewhere if they don't want to lose it.

**Comment by tobiaschielens** [comment]
This is indeed by design. There is no way to get the revine transactions. Good idea would be to include this in 
https://github.com/threefoldfoundation/tft-stellar/blob/master/wiki/wiki_3bot_connect_wallet.md or https://github.com/threefoldfoundation/tft-stellar/blob/master/wiki/wiki_tokens_on_stellar.md
